apiVersion: v1
kind: Service
metadata:
  labels:
    app: gitlab
  name: gitlab-svc
spec:
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      name: http
    - port: 443
      protocol: TCP
      name: https
    - port: 22
      protocol: TCP
      name: ssh
  selector:
    app: gitlab
